### ISSUE TITLE
not showing imgui 

### ISSUE THREAD

**Issue by winston321** [seanchas116/qtimgui#3]
I compiled and run your project, but a main window shown up, no imgui window, could you tell me what's wrong? I used visual studio 2015 to convert you .pro project to a vs project with qt-vs-tools-msvc2015-2.1.1， with Qt5.8 enviroment. thank you.

i actually hope this Dear ImGui  can work under Qt4.86 (since one of my project is constructed under this). is it possible? thank you .

winston

**Comment by spider-karma** [comment]
I have successfully displayed the imgui demo in a QOpenGLWidget using VS 2015 and Qt 5.9.9. I only had to promote the widget in Designer and invoke a timer on it to update.

**Comment by seanchas116** [comment]
Closing because the issue is old and the environments have changed a lot.
