### ISSUE TITLE
QT not forwarding "double mouse click" events 

### ISSUE THREAD

**Issue by crolando** [seanchas116/qtimgui#34]
I'm on windows 10. 
 A lot of the button widgets don't respond to rapid left-clicks.  

I found a bug in the event filter that blocks the QEvent::MouseButtonDblClick events from progressing to imgui. 

If I add this to the eventFilter switch statement, the double click events are passed to imgui, and the buttons then respond to rapid left clicks.

You can test this by checking the demo "double click" debug field to make sure the events are getting to imgui.  See below for source code change location, and test location.

![demo_location](https://user-images.githubusercontent.com/1946494/115122184-9e950d80-9f84-11eb-891e-8621086904d9.jpg)
![fix_line](https://user-images.githubusercontent.com/1946494/115122185-9e950d80-9f84-11eb-9a45-6b968ba9d32b.jpg)

**Comment by seanchas116** [comment]
Sorry for late response, fixed in https://github.com/seanchas116/qtimgui/commit/f256242056f54613a5fff07966cecff3c013c58b !
