### ISSUE TITLE
it seems not support the latest IMGUI version anymore.

### ISSUE THREAD

**Issue by lanmanck** [seanchas116/qtimgui#37]
Hi, when using latest IMGUI , there is a 'error ' pop up dialog show up again and again. But runs fine under your version. 
Would you fix it?
 thanks.

**Comment by seanchas116** [comment]
I [updated imgui to 1.86 (latest version) now](https://github.com/seanchas116/qtimgui/commit/9fd6b6c33796112aa1e7c3af9ec7de3bd445ccc7) and looks like it works well in my environment (macOS 12.1 & Qt 5.15.2).
Do you have some detailed error messages or a screenshot?

**Comment by lanmanck** [comment]
Hi, I downloaded latest qtimgui / imgui /implot today.
when runs demo-widget.exe ,it says:
![2022-01-22_163254](https://user-images.githubusercontent.com/3500166/150631083-15d046ae-9169-4beb-9984-28951e4a17fb.jpg)
I check your code. you did not update ImPlot, maybe it's the reason?
By the way, ImPlot::DragLineX() is changed.

**Comment by lanmanck** [comment]
after update to imgui @ 512c54b, it works now....

**Comment by seanchas116** [comment]
Thank you! I also updated ImPlot to 0.12. https://github.com/seanchas116/qtimgui/commit/3e481ca800530eae0a4bd7d53a8805585eb6c5c2
